### ISSUE TITLE
Gsuite Ggroups "applicationName" value "groups" is not allowed

### ISSUE THREAD

**Issue by Ryxias** [airbnb/streamalert#1036]
## Background

StreamAlert app for gsuite errors.

### Stack Trace

```
[ERROR] TypeError: Parameter "applicationName" value "groups" is not an allowed value 
in "['access_transparency', 'admin', 'calendar', 'drive', 'gcp', 'gplus', 'group', 'groups_enterprise', 
'login', 'mobile', 'rules', 'token', 'user_accounts']" 
Traceback (most recent call last): 
File "/var/task/streamalert/apps/main.py", line 30, in handler StreamAlertApp.get_app(event['app_type'])(event, context).gather() 
File "/var/task/streamalert/apps/app_base.py", line 395, in gather while (((self._gather() * self._POLL_BUFFER_MULTIPLIER) + self._sleep_seconds()) < 
File "/var/task/streamalert/apps/app_base.py", line 42, in _wrapper func(*args, **kwargs) 
File "/var/task/streamalert/apps/app_base.py", line 364, in _gather logs = self._gather_logs() 
File "/var/task/streamalert/apps/_apps/gsuite.py", line 143, in _gather_logs pageToken=self._next_page_token 
File "/var/task/googleapiclient/discovery.py", line 764, in method (name, value, str(enums)))
```

**Comment by ryandeivert** [comment]
resolved with #1046
