### ISSUE TITLE
[apps] Duo Admin app: TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#1038]
## Background

```
[ERROR] TypeError: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/var/task/streamalert/apps/main.py", line 30, in handler
    StreamAlertApp.get_app(event['app_type'])(event, context).gather()
  File "/var/task/streamalert/apps/app_base.py", line 395, in gather
    while (((self._gather() * self._POLL_BUFFER_MULTIPLIER) + self._sleep_seconds()) <
  File "/var/task/streamalert/apps/app_base.py", line 42, in _wrapper
    func(*args, **kwargs)
  File "/var/task/streamalert/apps/app_base.py", line 364, in _gather
    logs = self._gather_logs()
  File "/var/task/streamalert/apps/_apps/duo.py", line 94, in _gather_logs
    return self._get_duo_logs(hostname, full_url)
  File "/var/task/streamalert/apps/_apps/duo.py", line 120, in _get_duo_logs
    params = {'mintime': str(int(self._last_timestamp + 1))}
```

## Desired Change

Fix the above bug.

**Comment by ryandeivert** [comment]
this happened due to a misconfigured state - not a bug. closing out.
