### ISSUE TITLE
[apps] box admin app: requests.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#1040]
## Background

```
Traceback (most recent call last):
File "/var/task/urllib3/connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/var/task/urllib3/connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "/var/lang/lib/python3.7/http/client.py", line 1336, in getresponse
response.begin()
File "/var/lang/lib/python3.7/http/client.py", line 306, in begin
version, status, reason = self._read_status()
File "/var/lang/lib/python3.7/http/client.py", line 267, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/var/lang/lib/python3.7/socket.py", line 589, in readinto
return self._sock.recv_into(b)
File "/var/lang/lib/python3.7/ssl.py", line 1071, in recv_into
return self.read(nbytes, buffer)
File "/var/lang/lib/python3.7/ssl.py", line 929, in read
return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/requests/adapters.py", line 449, in send
timeout=timeout
File "/var/task/urllib3/connectionpool.py", line 641, in urlopen
_stacktrace=sys.exc_info()[2])
File "/var/task/urllib3/util/retry.py", line 368, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/var/task/urllib3/packages/six.py", line 686, in reraise
raise value
File "/var/task/urllib3/connectionpool.py", line 603, in urlopen
chunked=chunked)
File "/var/task/urllib3/connectionpool.py", line 389, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/var/task/urllib3/connectionpool.py", line 307, in _raise_timeout
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.box.com', port=443): Read timed out. (read timeout=3.05)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/streamalert/apps/app_base.py", line 58, in _wrapper
return func(*args, **kwargs)
File "/var/task/streamalert/apps/_apps/box.py", line 147, in _make_request
return _perform_request()
File "/var/task/streamalert/apps/_apps/box.py", line 128, in _perform_request
timeout=self._DEFAULT_REQUEST_TIMEOUT
File "/var/task/boxsdk/util/api_call_decorator.py", line 71, in call
return method(*args, **kwargs)
File "/var/task/boxsdk/client/client.py", line 1320, in make_request
return self._session.request(method, url, **kwargs)
File "/var/task/boxsdk/session/session.py", line 157, in request
response = self._prepare_and_send_request(method, url, **kwargs)
File "/var/task/boxsdk/session/session.py", line 388, in _prepare_and_send_request
network_response = self._send_request(request, **kwargs)
File "/var/task/boxsdk/session/session.py", line 608, in _send_request
return super(AuthorizedSession, self)._send_request(request, **kwargs)
File "/var/task/boxsdk/session/session.py", line 508, in _send_request
**request_kwargs
File "/var/task/boxsdk/network/default_network.py", line 43, in request
request_response=self._session.request(method, url, **kwargs),
File "/var/task/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/var/task/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/var/task/requests/adapters.py", line 529, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.box.com', port=443): Read timed out. (read timeout=3.05)
```

## Desired Change

Fix above error

**Comment by ryandeivert** [comment]
fixed with #1057
