### ISSUE TITLE
[bug][test] AttributeError: 'Namespace' object has no attribute 'stats' when run classifier test

### ISSUE THREAD

**Issue by chunyong-lin** [airbnb/streamalert#1044]
## Background
PR #1019 introduced `stats` argument from cli command line, but is not always exist. It exists in rule test parser, but not classifier parser. When I run `python manage.py test classifier` it throws error `AttributeError: 'Namespace' object has no attribute 'stats'`. 
### Description
I did print out the value of options when it passed to test handler, it doesn't has `stats` attribute. 
```
Namespace(command='test', debug=False, files=set(), files_dir='tests/integration/rules/', quiet=False, rules=set(), subcommand='classifier', verbose=False, **{'test subcommand': 'classifier'})
```

The full traceback for future reference
```
python manage.py test classifier                 

Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    main()
  File "manage.py", line 112, in main
    sys.exit(not cli_runner(options))
  File "/Users/xxxxx/xxx/streamalert/streamalert_cli/runner.py", line 70, in cli_runner
    result = cmds[args.command](args)
  File "/Users/xxxxx/xxx/streamalert/streamalert_cli/runner.py", line 126, in <lambda>
    command: lambda opts, cmd=cli_command: cmd.handler(opts, config)
  File "/Users/xxxxx/xxx/streamalert/streamalert_cli/test/handler.py", line 198, in handler
    result = result and TestRunner(options, config).run()
  File "/Users/xxxxx/xxx/streamalert/streamalert_cli/test/handler.py", line 237, in __init__
    if options.stats:
AttributeError: 'Namespace' object has no attribute 'stats'
```
### Steps to Reproduce
Run
```
python manage.py test classifier
```
## Desired Change
* Handle `AttributeError` when refers to `stats` attribute in classifier testing.
* Add classifier test to CI `.travis.yml` to catch such failure in the future.

**Comment by chunyong-lin** [comment]
This issue is fixed in PR #1045 😄
