### ISSUE TITLE
[bug] Sanitize log name if there have dots

### ISSUE THREAD

**Issue by chunyong-lin** [airbnb/streamalert#1186]
## Background
When we have `log:name.with.dots.bala` in the `conf/schemas/weird_logs.json` or `conf/logs.json`, the `create_table` and `generate_data_table_schema` methods will throw `KeyError`.

https://github.com/airbnb/streamalert/blob/f8a9da465f2f9d187cc8300a0f0e2e1f013c1e4a/streamalert_cli/athena/handler.py#L405
https://github.com/airbnb/streamalert/blob/f8a9da465f2f9d187cc8300a0f0e2e1f013c1e4a/streamalert_cli/athena/helpers.py#L213

It is still a mystery to me that how did we create carbonblack tables correctly before.

### Steps to Reproduce
* The issue can be reproduce when running `create_table` cli to create an Athena table
```
python manage.py athena create-table  --bucket nobody2020030420-streamalert-data  --table-name carbonblack_alert_status_updated

Traceback (most recent call last):
  File "manage.py", line 116, in <module>
    main()
  File "manage.py", line 112, in main
    sys.exit(not cli_runner(options))
  File "/Users/nobody/Work/ext_streamalert/streamalert_cli/runner.py", line 70, in cli_runner
    result = cmds[args.command](args)
  File "/Users/nobody/Work/ext_streamalert/streamalert_cli/runner.py", line 126, in <lambda>
    command: lambda opts, cmd=cli_command: cmd.handler(opts, config)
  File "/Users/nobody/Work/ext_streamalert/streamalert_cli/athena/handler.py", line 187, in handler
    options.schema_override
  File "/Users/nobody/Work/ext_streamalert/streamalert_cli/athena/handler.py", line 406, in create_table
    log_info = config['logs'][table.replace('_', ':', 1)]
KeyError: 'carbonblack:alert_status_updated'
```

* I also added unit test cases to reproduce this issue.

## Desired Change
* Sanitize log name by replacing `.` with `_`.
* Increase the unit test coverage for the code under `streamalert_cli/`

**Comment by chunyong-lin** [comment]
This should be fixed.
