### ISSUE TITLE
insecure string pickle error

### ISSUE THREAD

**Issue by zbuc** [airbnb/streamalert#200]
I cloned the repository at commit `68ace7f6b30dc60a851e0e95f3117740c5ec0093` and am trying to follow the setup instructions from the documentation.

I configured `conf/global.json` and `conf/lambda.json` with my values for `aws_account_id` and `prefix`, created my own cluster (just by copying the existing `prod.json` and changing the ID), and tried running `python stream_alert_cli.py terraform build` from within my virtual environment, as per the instructions found at https://streamalert.readthedocs.io/clusters.html

After doing so, I received an error message about an insecure string pickle. I haven't dug through the code yet to see what exactly is causing it, but I haven't made any changes beyond what the documentation told me to do.

Stack trace:

```
StreamAlertCLI [INFO]: Issues? Report here: https://github.com/airbnb/streamalert/issues
Traceback (most recent call last):
  File "stream_alert_cli.py", line 203, in <module>
    main()
  File "stream_alert_cli.py", line 198, in main
    cli_runner(options)
  File "/Users/chris/repos/corpsec/log_all_the_things/streamalert/stream_alert_cli/runner.py", line 65, in cli_runner
    terraform_handler(options)
  File "/Users/chris/repos/corpsec/log_all_the_things/streamalert/stream_alert_cli/runner.py", line 98, in terraform_handler
    terraform_check()
  File "/Users/chris/repos/corpsec/log_all_the_things/streamalert/stream_alert_cli/runner.py", line 92, in terraform_check
    quiet=True)
  File "/Users/chris/repos/corpsec/log_all_the_things/streamalert/stream_alert_cli/runner.py", line 205, in run_command
    return helpers.run_command(args, **kwargs)
  File "/Users/chris/repos/corpsec/log_all_the_things/streamalert/stream_alert_cli/helpers.py", line 58, in run_command
    subprocess.check_call(runner_args, stdout=stdout_option, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

**Comment by zbuc** [comment]
I looked at line 92 of `streamalert/stream_alert_cli/runner.py` and this seemed to be happening because I didn't have terraform installed.

It seems like the intended error message didn't properly display.

**Comment by ryandeivert** [comment]
Thanks for the in-depth write up - working on this now!
