### ISSUE TITLE
Bug: Check for valid credentials before deploying

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#217]
## Background

If your environment changed since you configured your cluster, your AWS credentials may not be loaded anymore.  In that case, you will get the following error when trying to deploy:

```
StreamAlertCLI [INFO]: Issues? Report here: https://github.com/airbnb/streamalert/issues
StreamAlertCLI [INFO]: Generating cluster file: main.tf
StreamAlertCLI [INFO]: Generating cluster file: prod.tf
StreamAlertCLI [INFO]: Installing third-party libraries: netaddr, jsonpath_rw
Creating Lambda package: /var/folders/_v/tz_z2qgs5cj75jy0l_3s72mh0000gn/T/rule_processor_1.3.0_20170707_T211801.zip
Package Successfully Created!
Uploading StreamAlert package to S3
An error occurred while uploading rule_processor_1.3.0_20170707_T211801.zip
Traceback (most recent call last):
  File "stream_alert_cli.py", line 209, in <module>
    main()
  File "stream_alert_cli.py", line 204, in main
    cli_runner(options)
  File "/Users/jack/Code/streamalert/stream_alert_cli/runner.py", line 59, in cli_runner
    lambda_handler(options)
  File "/Users/jack/Code/streamalert/stream_alert_cli/runner.py", line 75, in lambda_handler
    deploy(options)
  File "/Users/jack/Code/streamalert/stream_alert_cli/runner.py", line 399, in deploy
    packages.append(deploy_rule_processor())
  File "/Users/jack/Code/streamalert/stream_alert_cli/runner.py", line 380, in deploy_rule_processor
    rule_package.create_and_upload()
  File "/Users/jack/Code/streamalert/stream_alert_cli/package.py", line 67, in create_and_upload
    if self._upload(package_path):
  File "/Users/jack/Code/streamalert/stream_alert_cli/package.py", line 211, in _upload
    ServerSideEncryption='AES256'
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/client.py", line 530, in _make_api_call
    operation_model, request_dict)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/jack/Code/streamalert/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))
```

This should be handled more gracefully.  We could do a basic check to see if the account number declared matches the response of this command:

`aws sts get-caller-identity --output text --query Account`

## Desired Outcome

Before any deployment commands are run, check for valid credentials.

**Comment by ryandeivert** [comment]
As part of this, we should probably also do a check to see if there are any creds at all. It's possible to be in a shell without environment variables set or without having run `aws configure`. Just something to keep in mind when fixing this. This is fairly easy to do just with:

```
import boto3
session = boto3.Session()
if not session.get_credentials():
    # Handle error here and return
    return
```
