### ISSUE TITLE
KeyError when creating package for athena_partition_refresh

### ISSUE THREAD

**Issue by VVMichaelSawyer** [airbnb/streamalert#241]
When executing `TF_LOG=DEBUG python ./stream_alert_cli.py terraform init` with the latest code, I receive the following error message:

```
StreamAlertCLI [INFO]: Creating package for athena_partition_refresh
Traceback (most recent call last):
  File "./stream_alert_cli.py", line 436, in <module>
    main()
  File "./stream_alert_cli.py", line 431, in main
    cli_runner(options)
  File "/Users/michaelsawyer/dev/streamalert/stream_alert_cli/runner.py", line 71, in cli_runner
    terraform_handler(options)
  File "/Users/michaelsawyer/dev/streamalert/stream_alert_cli/runner.py", line 255, in terraform_handler
    deploy(deploy_opts('all'))
  File "/Users/michaelsawyer/dev/streamalert/stream_alert_cli/runner.py", line 527, in deploy
    packages.append(_deploy_athena_partition_refresh())
  File "/Users/michaelsawyer/dev/streamalert/stream_alert_cli/runner.py", line 499, in _deploy_athena_partition_refresh
    athena_package.create_and_upload()
  File "/Users/michaelsawyer/dev/streamalert/stream_alert_cli/package.py", line 68, in create_and_upload
    if not self._resolve_third_party(temp_package_path):
  File "/Users/michaelsawyer/dev/streamalert/stream_alert_cli/package.py", line 183, in _resolve_third_party
    third_party_libs = self.config['lambda'][self.config_key]['third_party_libraries']
KeyError: 'athena_partition_refresh_config'
```

**Comment by jacknagz** [comment]
Thanks @VVMichaelSawyer, I'll push a fix today.  In the meantime, please checkout a tagged release:

`$ git checkout tags/1.4.0`
