### ISSUE TITLE
Bug: Rule processor Firehose bug - `error: [Errno 104] Connection reset by peer`

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#478]
## Background

Observed the following traceback in CloudWatch logs:
```
[Errno 104] Connection reset by peer: error
Traceback (most recent call last):
File "/var/task/stream_alert/rule_processor/main.py", line 39, in handler
StreamAlert(context).run(event)
File "/var/task/stream_alert/rule_processor/handler.py", line 172, in run
self._send_to_firehose()
File "/var/task/stream_alert/rule_processor/handler.py", line 348, in _send_to_firehose
self._firehose_request_helper(stream_name, sized_batch)
File "/var/task/stream_alert/rule_processor/handler.py", line 304, in _firehose_request_helper
resp = firehose_request_wrapper()
File "/var/task/backoff/_sync.py", line 42, in retry
ret = target(*args, **kwargs)
File "/var/task/backoff/_sync.py", line 85, in retry
ret = target(*args, **kwargs)
File "/var/task/stream_alert/rule_processor/handler.py", line 299, in firehose_request_wrapper
in record_batch])
File "/var/runtime/botocore/client.py", line 312, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 592, in _make_api_call
operation_model, request_dict)
File "/var/runtime/botocore/endpoint.py", line 141, in make_request
return self._send_request(request_dict, operation_model)
File "/var/runtime/botocore/endpoint.py", line 170, in _send_request
success_response, exception):
File "/var/runtime/botocore/endpoint.py", line 249, in _needs_retry
caught_exception=caught_exception, request_dict=request_dict)
File "/var/runtime/botocore/hooks.py", line 227, in emit
return self._emit(event_name, kwargs)
File "/var/runtime/botocore/hooks.py", line 210, in _emit
response = handler(**kwargs)
File "/var/runtime/botocore/retryhandler.py", line 183, in __call__
if self._checker(attempts, response, caught_exception):
File "/var/runtime/botocore/retryhandler.py", line 251, in __call__
caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 269, in _should_retry
return self._checker(attempt_number, response, caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 317, in __call__
caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 223, in __call__
attempt_number, caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 359, in _check_caught_exception
raise caught_exception
error: [Errno 104] Connection reset by peer
```

## Desired Change

No more crashes :)

**Comment by ryandeivert** [comment]
I noticed this is still occurring occasionally. Reopening to investigate & maybe add a test to make sure this is caught properly.

**Comment by austinbyers** [comment]
Can confirm this still happens, especially with very high-volume rule processors

**Comment by ryandeivert** [comment]
This is still occurring for us, so reopening so we do not forget to investigate.

**Comment by chunyong-lin** [comment]
This issue has been fixed by PR #736

**Comment by ryandeivert** [comment]
this still happens occasionally, so reopening to track

**Comment by ryandeivert** [comment]
this error has not occurred since changes to boto3 packaging in v2.1.0. we will continue to monitor for future occurrences and re-open if necessary.
