### ISSUE TITLE
Bug: Lambda Running out of Disk Space

### ISSUE THREAD

**Issue by jacknagz** [airbnb/streamalert#613]
### Description

Before downloading files from S3 to Lambda via S3 Events, there is no check in the `Payload` class on the currently utilized disk space.

https://github.com/airbnb/streamalert/blob/4a43f096aac97a5c196334b2b9991e0d4406d4da/stream_alert/rule_processor/payload.py#L201-L218

From AWS docs:

> Each Lambda function receives an additional 500MB of non-persistent disk space in its own /tmp directory. The /tmp directory can be used for loading additional resources like dependency libraries or data sets during function initialization.

### Steps to Reproduce

Try downloading a large file:

```
[Errno 28] No space left on device: IOError
Traceback (most recent call last):
File "/var/task/stream_alert/rule_processor/main.py", line 59, in handler
StreamAlert(context).run(event)
File "/var/task/stream_alert/rule_processor/handler.py", line 121, in run
payload_with_normalized_records.extend(self._process_alerts(payload))
File "/var/task/stream_alert/rule_processor/handler.py", line 175, in _process_alerts
for record in payload.pre_parse():
File "/var/task/stream_alert/rule_processor/payload.py", line 155, in pre_parse
s3_file = self._get_object()
File "/var/task/stream_alert/rule_processor/payload.py", line 246, in _get_object
return self._download_object(region, bucket, key)
File "/var/task/stream_alert/rule_processor/payload.py", line 218, in _download_object
client.download_fileobj(bucket, key, data)
File "/var/runtime/boto3/s3/inject.py", line 570, in download_fileobj
return future.result()
File "/var/runtime/s3transfer/futures.py", line 73, in result
return self._coordinator.result()
File "/var/runtime/s3transfer/futures.py", line 233, in result
raise self._exception
IOError: [Errno 28] No space left on device
```

## Desired Change

Check for the currently utilized disk space in `/tmp` prior to downloading files.  If it's not able to download the file at hand, log the current contents of the directory as an `ERROR`, and fail the Lambda function to invoke retry logic.

**Comment by ryandeivert** [comment]
Could we just wrap the download code in a `try/except` that catches `IOError`s instead of checking tmp?

**Comment by jacknagz** [comment]
@ryandeivert, we could, but I still think it's valuable to understand what's in `/tmp`
