### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#633]
## Background

Observed crash in apps function related to invoking the rule processor:
```
Traceback (most recent call last):
File "/var/task/app_integrations/main.py", line 39, in handler
app.gather()
File "/var/task/app_integrations/apps/app_base.py", line 438, in gather
while (self._gather() + self._sleep_seconds() <
File "/var/task/app_integrations/apps/app_base.py", line 423, in _gather
exec_time = Decimal(timeit(do_gather, number=1))
File "/usr/lib64/python2.7/timeit.py", line 237, in timeit
return Timer(stmt, setup, timer).timeit(number)
File "/usr/lib64/python2.7/timeit.py", line 202, in timeit
timing = self.inner(it, self.timer)
File "/usr/lib64/python2.7/timeit.py", line 100, in inner
_func()
File "/var/task/app_integrations/apps/app_base.py", line 412, in do_gather
self._batcher.send_logs(self._config['function_name'], logs)
File "/var/task/app_integrations/batcher.py", line 53, in send_logs
if self._send_logs_to_stream_alert(source_function, logs):
File "/var/task/app_integrations/batcher.py", line 114, in _send_logs_to_stream_alert
Qualifier='production'
File "/var/runtime/botocore/client.py", line 317, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 615, in _make_api_call
raise error_class(parsed_response, operation_name)
ServiceException: An error occurred (ServiceException) when calling the Invoke operation (reached max retries: 4): An error occurred and the request cannot be processed.
```

## Desired Change

Investigate what's going on and not crash ;)

**Comment by usamaneurotrack** [comment]
any update on this issue? I encounter this issue today on our app as well.
