### ISSUE TITLE
Alert Merger - Connection reset by peer error

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#789]
## Background

Observed a traceback in the alert merger lambda function.

### Description

Traceback observed:

```
[Errno 104] Connection reset by peer: error
Traceback (most recent call last):
File "/var/task/stream_alert/alert_merger/main.py", line 192, in handler
AlertMerger.get_instance().dispatch()
File "/var/task/stream_alert/alert_merger/main.py", line 147, in dispatch
alerts = self._get_alerts(rule_name)
File "/var/task/stream_alert/alert_merger/main.py", line 78, in _get_alerts
for record in self.table.get_alert_records(rule_name, self.alert_proc_timeout):
File "/var/task/stream_alert/shared/alert_table.py", line 98, in get_alert_records
for item in self._paginate(self._table.query, kwargs):
File "/var/task/stream_alert/shared/alert_table.py", line 50, in _paginate
response = func(**func_kwargs)
File "/var/runtime/boto3/resources/factory.py", line 520, in do_action
response = action(self, *args, **kwargs)
File "/var/runtime/boto3/resources/action.py", line 83, in __call__
response = getattr(parent.meta.client, operation_name)(**params)
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 599, in _make_api_call
operation_model, request_dict)
File "/var/runtime/botocore/endpoint.py", line 148, in make_request
return self._send_request(request_dict, operation_model)
File "/var/runtime/botocore/endpoint.py", line 177, in _send_request
success_response, exception):
File "/var/runtime/botocore/endpoint.py", line 273, in _needs_retry
caught_exception=caught_exception, request_dict=request_dict)
File "/var/runtime/botocore/hooks.py", line 227, in emit
return self._emit(event_name, kwargs)
File "/var/runtime/botocore/hooks.py", line 210, in _emit
response = handler(**kwargs)
File "/var/runtime/botocore/retryhandler.py", line 183, in __call__
if self._checker(attempts, response, caught_exception):
File "/var/runtime/botocore/retryhandler.py", line 251, in __call__
caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 269, in _should_retry
return self._checker(attempt_number, response, caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 317, in __call__
caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 223, in __call__
attempt_number, caught_exception)
File "/var/runtime/botocore/retryhandler.py", line 359, in _check_caught_exception
raise caught_exception
error: [Errno 104] Connection reset by peer
```

### Steps to Reproduce

N/A

## Desired Change

Maybe use a boto config with shortened timeout or handle the exception (if necessary). I'd probably opt for not handling the exception since we want to know if this occurs.

**Comment by ryandeivert** [comment]
this error has not occurred since changes to boto3 packaging in v2.1.0. we will continue to monitor for future occurrences and re-open if necessary.
