### ISSUE TITLE
[bug] slack access app - ChunkedEncodingError, connection reset by peer

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#817]
## Background

Traceback:
```
("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer')): ChunkedEncodingError
Traceback (most recent call last):
File "/var/task/stream_alert/apps/main.py", line 30, in handler
StreamAlertApp.get_app(event['app_type'])(event, context).gather()
File "/var/task/stream_alert/apps/app_base.py", line 379, in gather
while (((self._gather() * self._POLL_BUFFER_MULTIPLIER) + self._sleep_seconds()) <
File "/var/task/stream_alert/apps/app_base.py", line 38, in _wrapper
func(*args, **kwargs)
File "/var/task/stream_alert/apps/app_base.py", line 348, in _gather
logs = self._gather_logs()
File "/var/task/stream_alert/apps/_apps/slack.py", line 112, in _gather_logs
success, response = self._make_post_request(url, headers, data, False)
File "/var/task/stream_alert/apps/app_base.py", line 54, in _wrapper
return func(*args, **kwargs)
File "/var/task/stream_alert/apps/app_base.py", line 331, in _make_post_request
data=data, timeout=self._DEFAULT_REQUEST_TIMEOUT)
File "/var/task/requests/api.py", line 112, in post
return request('post', url, data=data, json=json, **kwargs)
File "/var/task/requests/api.py", line 58, in request
return session.request(method=method, url=url, **kwargs)
File "/var/task/requests/sessions.py", line 508, in request
resp = self.send(prep, **send_kwargs)
File "/var/task/requests/sessions.py", line 658, in send
r.content
File "/var/task/requests/models.py", line 823, in content
self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
File "/var/task/requests/models.py", line 748, in generate
raise ChunkedEncodingError(e)
ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
```

### Steps to Reproduce

N/A

## Desired Change

Decide if this case should be handled gracefully. If not, close this issue out as won't fix.

**Comment by ryandeivert** [comment]
this error has not occurred since changes to boto3 packaging in v2.1.0. we will continue to monitor for future occurrences and re-open if necessary.

**Comment by chunyong-lin** [comment]
`ChunkedEncodingError` is back 😒  I have observed this error few time from different StreamAlert Apps.

**Comment by ryandeivert** [comment]
still seeing this as of 2020-03-12
