### ISSUE TITLE
[bug] s3: [Errno 104] Connection reset by peer: error

### ISSUE THREAD

**Issue by ryandeivert** [airbnb/streamalert#828]
## Background

```
[Errno 104] Connection reset by peer: error
Traceback (most recent call last):
File "/var/task/stream_alert/rule_processor/main.py", line 26, in handler
StreamAlert(context).run(event)
File "/var/task/stream_alert/rule_processor/handler.py", line 64, in __init__
self._rules_engine = RulesEngine(self.config, *rule_import_paths)
File "/var/task/stream_alert/rule_processor/rules_engine.py", line 47, in __init__
RulesEngine._LOOKUP_TABLES = lookup_tables.download_s3_objects()
File "/var/task/stream_alert/shared/lookup_tables.py", line 67, in download_s3_objects
data = s3_object.get('Body').read()
File "/var/runtime/botocore/response.py", line 76, in read
chunk = self._raw_stream.read(amt)
File "/var/runtime/botocore/vendored/requests/packages/urllib3/response.py", line 239, in read
data = self._fp.read()
File "/usr/lib64/python2.7/httplib.py", line 596, in read
s = self._safe_read(self.length)
File "/usr/lib64/python2.7/httplib.py", line 703, in _safe_read
chunk = self.fp.read(min(amt, MAXAMOUNT))
File "/usr/lib64/python2.7/socket.py", line 384, in read
data = self._sock.recv(left)
File "/usr/lib64/python2.7/ssl.py", line 756, in recv
return self.read(buflen)
File "/usr/lib64/python2.7/ssl.py", line 643, in read
v = self._sslobj.read(len)
error: [Errno 104] Connection reset by peer
```
## Desired Change

Handle appropriately.

**Comment by ryandeivert** [comment]
this error has not occurred since changes to boto3 packaging in v2.1.0. we will continue to monitor for future occurrences and re-open if necessary.
