### ISSUE TITLE
[bug] ParamValidationError (Invalid length for parameter Records)

### ISSUE THREAD

**Issue by chunyong-lin** [airbnb/streamalert#894]
## Background
Observe `ParamValidationError` exception while sending batch records to firehose occasionally.
```
Parameter validation failed:
Invalid length for parameter Records, value: 0, valid range: 1-inf: ParamValidationError
Traceback (most recent call last):
File "/var/task/stream_alert/classifier/main.py", line 27, in handler
Classifier().run(event.get('Records', []))
File "/var/task/stream_alert/classifier/classifier.py", line 253, in run
self.firehose.send(self._payloads)
File "/var/task/stream_alert/classifier/clients/firehose.py", line 393, in send
response = self._send_batch(stream_name, record_batch)
File "/var/task/stream_alert/classifier/clients/firehose.py", line 275, in _send_batch
return _firehose_request_helper(records_data)
File "/var/task/backoff/_sync.py", line 48, in retry
ret = target(*args, **kwargs)
File "/var/task/backoff/_sync.py", line 99, in retry
ret = target(*args, **kwargs)
File "/var/task/stream_alert/classifier/clients/firehose.py", line 256, in _firehose_request_helper
response = self._client.put_record_batch(DeliveryStreamName=stream_name, Records=data)
File "/var/task/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/task/botocore/client.py", line 634, in _make_api_call
api_params, operation_model, context=request_context)
File "/var/task/botocore/client.py", line 682, in _convert_to_request_dict
api_params, operation_model)
File "/var/task/botocore/validate.py", line 297, in serialize_to_request
raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid length for parameter Records, value: 0, valid range: 1-inf
```

## Desired Change
We probably should take another look at data length checking in [_send_batch](https://github.com/airbnb/streamalert/blob/master/stream_alert/classifier/clients/firehose.py#L256) in firehose client. Skip if data length is 0.

**Comment by ryandeivert** [comment]
this is fixed with #903 👏
