### ISSUE TITLE
slack app throws JSONDecodeError

### ISSUE THREAD

**Issue by chunyong-lin** [airbnb/streamalert#998]
## Background
Occasionally, slack app may throw out `JSONDecodeError` after upgrade StreamAlert to python3. Note: the issue only exists in release-3-0-0 branch as I know.
```
[ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/var/task/stream_alert/apps/main.py", line 30, in handler
    StreamAlertApp.get_app(event['app_type'])(event, context).gather()
  File "/var/task/stream_alert/apps/app_base.py", line 384, in gather
    while (((self._gather() * self._POLL_BUFFER_MULTIPLIER) + self._sleep_seconds()) <
  File "/var/task/stream_alert/apps/app_base.py", line 41, in _wrapper
    func(*args, **kwargs)
  File "/var/task/stream_alert/apps/app_base.py", line 353, in _gather
    logs = self._gather_logs()
  File "/var/task/stream_alert/apps/_apps/slack.py", line 116, in _gather_logs
    success, response = self._make_post_request(url, headers, data, False)
  File "/var/task/stream_alert/apps/app_base.py", line 57, in _wrapper
    return func(*args, **kwargs)
  File "/var/task/stream_alert/apps/app_base.py", line 338, in _make_post_request
    return self._check_http_response(response), response.json()
  File "/var/task/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/var/lang/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/var/lang/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

## Desired Change
Find out the root cause and handle the `JSONDecodeError`.

**Comment by chunyong-lin** [comment]
This issue was triggered when slack api endpoint returns status code `504` (Gateway Timeout).

**Comment by chunyong-lin** [comment]
The root cause is when `requests` response returns Gateway Timeout with status_code 504, the `response` object will return empty string and raises JSONDecoderError a when `.json()` refers to. See https://github.com/psf/requests/blob/428f7a275914f60a8f1e76a7d69516d617433d30/requests/models.py#L871. The solution is to handle `JSONDecoderError` by returning `False, None`.
